# dependabot configuration available at: https://docs.github.com/en/code-security/dependabot
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:30"
      timezone: "UTC"
    target-branch: develop
    reviewers:
      - fborriello
    labels:
      - configuration
      - update
      - github-actions-lib
  # Maintain dependencies for maven
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "11:30"
      timezone: "UTC"
    open-pull-requests-limit: 10
    target-branch: develop
    reviewers:
      - fborriello
    labels:
      - configuration
      - update
      - dependencies